import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/JsonLd";
import { getCurrentUser } from "@/lib/get-current-user";
import { getActiveGameBySlug } from "@/lib/games";
import { SARGAM_PAGE, SITE } from "@/lib/site";
import { breadcrumbNode, videoGameNode } from "@/lib/structured-data";
import Sargam from "./sargam-client";

/// The catalog row behind this route. The URL and the branding are "sargam";
/// the Game record is still slugged "songless" (see prisma/seed.ts), so the two
/// deliberately differ — don't "fix" one to match the other.
const GAME_SLUG = "songless";

/// The page's copy lives in GAME_PAGES (src/lib/site.ts), not in the Game row
/// and not inline here.
///
/// Not the DB, because Game.name/tagline are operational copy ("Songless",
/// "Name the track before the clip runs out.") — what a search result needs is
/// the brand name plus the hook, and it has to keep rendering identically if
/// Postgres is unreachable while metadata resolves.
///
/// Not inline, because the same three strings are also what the sitemap lists
/// and what the JSON-LD VideoGame node describes. One copy means the markup
/// can't end up advertising a headline the page no longer shows.
const { path: PATH, headline: TITLE, description: DESCRIPTION } = SARGAM_PAGE;

export const metadata: Metadata = {
  // Rendered as "… · Cluecade" by the title.template in the root layout.
  title: TITLE,
  description: DESCRIPTION,
  // Relative — resolved against metadataBase (NEXT_PUBLIC_APP_URL) in the root
  // layout. Pinning it matters here because "/" redirects to this path: without
  // a canonical, crawlers that follow the redirect can still treat the two URLs
  // as competing copies of the same page.
  alternates: { canonical: PATH },
  keywords: [...SARGAM_PAGE.keywords],
  applicationName: SITE.name,
  category: "games",
  openGraph: {
    type: "website",
    url: PATH,
    siteName: SITE.name,
    // openGraph.title is not run through title.template, so the suffix is
    // spelled out to match what the tab and the SERP entry show.
    title: `${TITLE} · ${SITE.name}`,
    description: DESCRIPTION,
    locale: SITE.locale,
    // 1200x630, generated by scripts/generate-brand-assets.ts. The 2048x768
    // wordmark this used to point at is 2.67:1, and every major scraper crops
    // that to about 1.91:1 — taking a slice out of the logo.
    images: [SARGAM_PAGE.ogImage],
  },
  twitter: {
    card: "summary_large_image",
    title: `${TITLE} · ${SITE.name}`,
    description: DESCRIPTION,
    images: [SARGAM_PAGE.ogImage.url],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      // The default preview caps are conservative: a thumbnail-sized image and
      // a ~160 character snippet. This is the page we most want a full-width
      // card for, and it has no paywalled or licensed text to protect.
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default async function Page() {
  // Read straight from the data layer rather than fetching our own API: this is
  // a server component, and an HTTP round trip to ourselves buys nothing.
  const [user, game] = await Promise.all([
    getCurrentUser(),
    getActiveGameBySlug(GAME_SLUG),
  ]);

  // Only reachable if the seed hasn't been run — better a 404 than a board
  // rendered against an undefined reveal ladder.
  if (!game) notFound();

  return (
    <>
      {/* The Organization and WebSite nodes come from the root layout; these
          two describe this page and reference those by @id. The VideoGame node
          reads its rules off the row we just loaded rather than restating them,
          so retuning the ladder in admin updates the markup too. */}
      <JsonLd
        data={[
          videoGameNode(SARGAM_PAGE, {
            maxAttempts: game.maxAttempts,
            revealLadder: game.revealLadder,
          }),
          // Two crumbs, not one: the trail has to start at the site root for
          // Google to render it as a trail at all, and "/" is where the brand
          // name belongs even though it redirects here.
          breadcrumbNode([
            { name: SITE.name, path: "/" },
            { name: SARGAM_PAGE.name },
          ]),
        ]}
      />
      <Sargam user={user} game={game} />
    </>
  );
}
